In [1]:
def describe(x):
    print("Type: {}".format(x.type()))
    print("Shape/size: {}".format(x.shape))
    print("Values: \n{}".format(x))

In [2]:
import torch
import numpy as np

## Tensors Intro

### Creating tensors

In [5]:
describe(torch.rand(2, 3))  # uniform random
print()
describe(torch.randn(2, 3))  # random normal

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0.8988, 0.0179, 0.2958],
        [0.1424, 0.2628, 0.8773]])

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[-0.8690,  0.1634,  0.0940],
        [-0.4137,  1.3063, -0.5220]])


In [6]:
x = torch.ones(2, 3)
describe(x)

x.fill_(5)
describe(x)

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[1., 1., 1.],
        [1., 1., 1.]])
Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[5., 5., 5.],
        [5., 5., 5.]])


In [8]:
x = torch.Tensor([[1, 2, 3],
                 [4, 5, 6]])
describe(x)

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [10]:
npy = np.random.rand(2, 3)
describe(torch.from_numpy(npy))

Type: torch.DoubleTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0.2496, 0.5133, 0.5546],
        [0.2899, 0.1257, 0.4952]], dtype=torch.float64)


In [11]:
x = torch.FloatTensor([[1, 2, 3],
                      [4, 5, 6]])
describe(x)

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [12]:
x = x.long()
describe(x)

Type: torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[1, 2, 3],
        [4, 5, 6]])


In [13]:
x = torch.tensor([[1, 2, 3],
                 [4, 5, 6]], dtype=torch.int64)
describe(x)

Type: torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[1, 2, 3],
        [4, 5, 6]])


### Tensor Operations

In [16]:
describe(torch.add(x, x))

Type: torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[ 2,  4,  6],
        [ 8, 10, 12]])


In [17]:
describe(x + x)

Type: torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[ 2,  4,  6],
        [ 8, 10, 12]])


In [18]:
x = torch.arange(6)
describe(x)

Type: torch.LongTensor
Shape/size: torch.Size([6])
Values: 
tensor([0, 1, 2, 3, 4, 5])


In [19]:
x = x.view(2, 3)
describe(x)

Type: torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0, 1, 2],
        [3, 4, 5]])


In [20]:
describe(torch.sum(x, dim=0)) # row wise sum

Type: torch.LongTensor
Shape/size: torch.Size([3])
Values: 
tensor([3, 5, 7])


In [21]:
describe(torch.sum(x, dim=1)) # column wise sum

Type: torch.LongTensor
Shape/size: torch.Size([2])
Values: 
tensor([ 3, 12])


In [23]:
describe(torch.transpose(x, 0, 1))

Type: torch.LongTensor
Shape/size: torch.Size([3, 2])
Values: 
tensor([[0, 3],
        [1, 4],
        [2, 5]])


### Indexing, Slicing, and Joining

In [25]:
x = torch.arange(6).view(2, 3)
describe(x)

Type: torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0, 1, 2],
        [3, 4, 5]])


In [26]:
describe(x[:1, :2])

Type: torch.LongTensor
Shape/size: torch.Size([1, 2])
Values: 
tensor([[0, 1]])


In [27]:
describe(x[0,1])

Type: torch.LongTensor
Shape/size: torch.Size([])
Values: 
1


In [28]:
indices = torch.LongTensor([0, 2])
describe(torch.index_select(x, dim=1, index=indices))

Type: torch.LongTensor
Shape/size: torch.Size([2, 2])
Values: 
tensor([[0, 2],
        [3, 5]])


In [29]:
indices = torch.LongTensor([0, 0])
describe(torch.index_select(x, dim=0, index=indices))

Type: torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0, 1, 2],
        [0, 1, 2]])


In [30]:
row_indices = torch.arange(2).long()
col_indices = torch.LongTensor([0, 1])
describe(x[row_indices, col_indices])

Type: torch.LongTensor
Shape/size: torch.Size([2])
Values: 
tensor([0, 4])


In [35]:
describe(torch.cat([x, x], dim=1))

Type: torch.LongTensor
Shape/size: torch.Size([2, 6])
Values: 
tensor([[0, 1, 2, 0, 1, 2],
        [3, 4, 5, 3, 4, 5]])


In [36]:
describe(torch.stack([x, x]))

Type: torch.LongTensor
Shape/size: torch.Size([2, 2, 3])
Values: 
tensor([[[0, 1, 2],
         [3, 4, 5]],

        [[0, 1, 2],
         [3, 4, 5]]])


In [37]:
x2 = torch.ones(3, 2)
x2[:, 1] += 1
describe(x2)

Type: torch.FloatTensor
Shape/size: torch.Size([3, 2])
Values: 
tensor([[1., 2.],
        [1., 2.],
        [1., 2.]])


In [40]:
describe(torch.mm(x.float(), x2))

Type: torch.FloatTensor
Shape/size: torch.Size([2, 2])
Values: 
tensor([[ 3.,  6.],
        [12., 24.]])


In [6]:
x = torch.ones(2, 2, requires_grad=True)
describe(x)
print(x.grad)

Type: torch.FloatTensor
Shape/size: torch.Size([2, 2])
Values: 
tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
None


In [7]:
y = (x + 2) * (x + 5) + 3
describe(y)
print(x.grad)

Type: torch.FloatTensor
Shape/size: torch.Size([2, 2])
Values: 
tensor([[21., 21.],
        [21., 21.]], grad_fn=<AddBackward0>)
None


In [8]:
z = y.mean()
describe(z)
z.backward()
print(x.grad)

Type: torch.FloatTensor
Shape/size: torch.Size([])
Values: 
21.0
tensor([[2.2500, 2.2500],
        [2.2500, 2.2500]])


In [9]:
print(torch.mps.is_available())

AttributeError: module 'torch' has no attribute 'mps'

In [15]:
torch.device("mps")

device(type='mps')

In [29]:
device = torch.device("mps")
# device = torch.device("cpu")

In [30]:
print(device)

mps


In [31]:
x = torch.rand(3, 3).to(device)
describe(x)

Type: torch.mps.FloatTensor
Shape/size: torch.Size([3, 3])
Values: 
tensor([[0.7798, 0.7679, 0.9717],
        [0.0598, 0.2223, 0.6974],
        [0.4778, 0.5699, 0.7813]], device='mps:0')


In [32]:
y = torch.rand(3, 3)
x + y

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, mps:0 and cpu!

In [33]:
y = y.to(device)
x + y

tensor([[0.9359, 1.3191, 1.1340],
        [0.4247, 0.7132, 1.2324],
        [1.2754, 1.3771, 1.5528]], device='mps:0')

In [57]:
a = torch.rand(3, 1)
describe(a)
a = a.expand(3,4)
describe(a)

Type: torch.FloatTensor
Shape/size: torch.Size([3, 1])
Values: 
tensor([[0.5502],
        [0.0944],
        [0.0253]])
Type: torch.FloatTensor
Shape/size: torch.Size([3, 4])
Values: 
tensor([[0.5502, 0.5502, 0.5502, 0.5502],
        [0.0944, 0.0944, 0.0944, 0.0944],
        [0.0253, 0.0253, 0.0253, 0.0253]])
